#--- Set-up ---#
title: DanBi Han
description: DanBi Han's personal website
baseurl:  /
url: http://localhost:4000/ # https://danbihan.github.io/

#--- Notes ---#
# dictionary showing how notes are organized
# {subject: [subtopics]}
notes_dir:
  mathematics: 
    icon: <i class="fas fa-calculator"></i>
    topics:
      - topic1
      - topic2
  statistics:
    icon: <i class="fas fa-dice"></i>
    topics:
      - topic_a
  machine_learning: 
    icon: <i class="fas fa-robot"></i>
    topics:
      - null