# Website settings
title: DanBi Han
description: Personal website
keywords: blog, Jekyll, github, gh-pages
baseurl: /
url: https://danbihan.github.io
img_path: /static/assets/img/blog # I DON'T HAVE STATIC FOLDER!!!

# author
author:
  name: DH
  first_name: DanBi
  last_name: Han
  #cv: http://cv.jarrekk.com
  email: danbihan98@gmail.com
  #facebook_username: jiakunnj
  github_username: danbihan
  #linkedin_id: jarrekk
  avatar: /static/assets/img/landing/profile_pic.jpeg # I DON'T HAVE STATIC FOLDER!!!
  skill_icon1:
    - name: icon-python
    - name: icon-ruby
  skill_icon2:
    - name: icon-database
    - name: icon-git
  desc: Data scientist with experience in e-commerce and retail

## carousels
index_carousel: on
blog_carousel: on

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
